---
spring:
  profiles: discovery1
server:
  port: 8761

eureka:
  instance:
    hostname: discovery1
  client:
# 多个eureka service,使用ture
    registerWithEureka: false
    fetchRegistry: false
# This is for mutil services
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
#  server:
    # 解决警告: EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT.
    # RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.
#    enable-self-preservation: false

---
spring:
  profiles: discovery2
server:
  port: 8761
eureka:
  instance:
    hostname: discovery2
  client:
    service-url:
      defaultZone: http://192.168.2.5:${server.port}/eureka/