---
spring:
  profiles: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1
  client:
    region: zh-east-1
    availability-zones:
      zh-east-1: zh-east-1a,zh-east-1b
    service-url:
      zh-east-1a: http://localhost:8761/eureka
      zh-east-1b: http://localhost:8762/eureka

---
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
  client:
    region: zh-east-1
    availability-zones:
      zh-east-1: zh-east-1a,zh-east-1b
    service-url:
      zh-east-1a: http://localhost:8761/eureka
      zh-east-1b: http://localhost:8762/eureka

---
server:
  port: 8761
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eurekaserver:${server.port}/eureka/
  #  server:
      # 解决警告: EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT.
      # RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.
  #    enable-self-preservation: false